import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#FFF",
  },
  headerContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    alignItems: "center",
    borderBottomWidth: 1,
    borderColor: "#E8E8E8",
  },
  header: {
    paddingTop: 54,
    paddingBottom: 11,
    flexDirection: "row",
    alignItems: "flex-end",
    width: 343,
  },
  headerTitle: {
    marginLeft: "auto",
    marginRight: "auto",
    color: "#212121",
    fontSize: 17,
    fontWeight: 500,
  },
  photoContainer: {
    marginTop: 122,
    width: 343,
    height: 240,
    backgroundColor: "#F6F6F6",
    borderColor: "#E8E8E8",
    borderWidth: 1,
    borderRadius: 8,
    overflow: "hidden",
  },
  photoContent: {
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    height: "100%",
  },
  cameraIcon: {
    width: 60,
    height: 60,
    backgroundColor: "#FFFFFF",
    borderRadius: 30,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  underPhotoButton: {
    marginTop: 8,
    width: 343,
  },
  underPhotoButtonText: {
    fontWeight: 400,
    fontSize: 16,
    lineHeight: 18.75,
    color: "#BDBDBD",
  },
  textInput: {
    width: 343,
    height: 50,
  },
  locationInput: {
    marginTop: 16,
    height: 50,
    width: 343,
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    borderColor: "#E8E8E8",
    borderBottomWidth: 1,
  },
  publishButton: {
    justifyContent: "center",
    alignItems: "center",
    marginTop: 32,
    width: 343,
    height: 50,
    backgroundColor: "#E8E8E8",
    borderRadius: 25,
  },
  activeButton: {
    backgroundColor: "#FF6C00",
  },
  btnText: {
    color: "#BDBDBD",
  },
  activeBtnText: {
    color: "#fff",
  },
  btnTrash: {
    marginTop: "auto",
    marginBottom: 34,
    alignItems: "center",
    justifyContent: "center",
    width: 70,
    height: 40,
    backgroundColor: "#f6f6f6",
    borderRadius: 20,
  },
});
